enum Cart {
  RomOnly = 0x00,
  RomMBC1,
  RomMBC1Ram,
  RomMBC1RamBatt,
  RomMBC2,
  RomMBC2Batt,
  RomRam = 0x08,
  RomRamBatt,
  RomMMM1 = 0x0B,
  RomMM1Sram,
  RomMM1SramBatt,
  RomMBC3TimerBatt = 0x0F,
  RomMBC3TimerRamBatt,
  RomMBC3,
  RomMBC3Ram,
  RomMBC3RamBatt = 0x13,
  RomMBC5 = 0x19,
  RomMBC5Ram,
  RomMBC5RamBatt,
  RomMBC5Rumble,
  RomMBC5RumbleSram,
  RomMBC5RumbleSramBatt,
  PocketCamera,
  BandaiTAMA5 = 0xFD,
  HudsonHuC3 = 0xFE,
  HudonHuC1 = 0xFF
}